### ISSUE TITLE
Controllo validità URL e chiarezza messaggi 

### ISSUE THREAD

**Issue by LukeSavefrogs** [CoffeeStraw/VVVVID-Downloader#10]
Ciao,
Riscrivo di seguito l'idea avuta nel commento all'issue #8 in modo da iniziare un nuovo thread.. :)

Ho pensato che si potrebbe aggiungere un controllo per verificare che si tratti di un url valido. Ad esempio un utente potrebbe sbagliarsi e copiare **ttps://www.vvvvid.it/#!show/786/steinsgate-0** invece di **https://www.vvvvid.it/#!show/786/steinsgate-0** oppure **ww.vvvvid.it/#!show/786/steinsgate-0** invece di **www.vvvvid.it/#!show/786/steinsgate-0**. La differenza è sottile e, invece di trovarsi davanti ad un errore non parlante come

> Traceback (most recent call last):
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 176, in <module>
>     main()
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 171, in main
>     dl_from_vvvvid(line, requests_obj, ffmpeg_local)
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 30, in dl_from_vvvvid
>     show_id, url_name            = vvvvid_scraper.parse_url(url)
>   File "d:\Programmi\VVVVID-Downloader-FORK\VVVVID-Downloader\vvvvid_scraper.py", line 17, in parse_url
>     return re.search(pattern, url).groups()
> AttributeError: 'NoneType' object has no attribute 'groups'

gli si potrebbe presentare un messaggio del tipo: 

> URL non valido: ww.vvvvid.it/#!show/786/steinsgate-0

Questo anche perchè la tua regexp fa completo affidamento sul fatto che nell'url si trova "show", e in caso contrario restituisce il suddetto errore. Ciò significa che restituiscono errore anche URL come: 
- https://www.vvvvid.it/fandom/1/713/vvvvid-heroes/1216/541614/trailer
- https://www.vvvvid.it/fandom/5/242/horror-mania/231/541321/it-2-home-video
- https://www.vvvvid.it/channel/0/you/515708/video/l-attacco-dei-giganti-seconda-stagione-attacco-proiezione-sottomissione-e07

Quindi per il momento basterebbe aggiungere un controllo del tipo:
```python
if not re.match("(https?://)?www.vvvvid.it/show"):
    print("Errore - URL non valido: " + url)
```
Perlomeno in questo modo l'utente capisce che l'url non è supportato

![image](https://user-images.githubusercontent.com/33452387/81505619-e6310500-92f0-11ea-83f9-2c61872409c6.png)

**Comment by CoffeeStraw** [comment]
Stavo pensando che in realtà potremmo permettere che l'URL passato non sia totalmente corretto, ma dobbiamo segnalare invece se le due informazioni da estrarre dall'URL non sono valide:
- Lo showID, ovvero il numeretto dopo `show/` nell'URL;
- Il content name, ovvero il titolo del contenuto (URL formatted).

Quindi ho pensato che si potrebbe fare un doppio controllo:
https://github.com/CoffeeStraw/VVVVID-Downloader/blob/614bb6288348efe089ffa89ead6c4e710af77a7e/vvvvid_scraper.py#L9-L17
Qui si potrebbe controllare che le informazioni sono effettivamente estraibili dall'URL.

https://github.com/CoffeeStraw/VVVVID-Downloader/blob/614bb6288348efe089ffa89ead6c4e710af77a7e/vvvvid_scraper.py#L51-L92
Qui invece si potrebbe controllare se si ottiene un errore nel tentativo di andare a recuperare le informazioni dai server di VVVVID.

Teniamo conto che sono casi abbastanza rari, è difficile sbagliare un copia e incolla. Quindi vorrei mantenere il massimo delle performance gestendo il tutto con dei try-catch.

**Comment by LukeSavefrogs** [comment]
Hm... 
Per il primo punto ricapitolando:
- se l'url non si riferisce a VVVVID allora deve dare **errore**
- se l'url contiene "vvvvid.it/**show**" allora dovrebbe fare il controllo se sono presenti **showID** e **content name**
- altrimenti va in **download diretto**

Per il secondo punto non ho ben capito cosa intendi con 

> Qui invece si potrebbe controllare se si ottiene un errore nel tentativo di andare a recuperare le informazioni dai server di VVVVID.

**Comment by CoffeeStraw** [comment]
Per il primo punto se non sono presenti o showID o content_name validi (magari uno ha copiato l'indirizzo fino alla fine dello showID), allora dovrebbe ritornare errore in realtà, non proseguire.

Nel secondo punto intendevo che anche un solo carattere mancante (o di troppo) nello `show_id` o nel `content_name` potrebbe causare un errore, poiché il programma non otterrebbe un responso valido dalle API di VVVVID e andrebbe in eccezione.

**Comment by CoffeeStraw** [comment]
Risolta! Se ci sono altri controlli che si possono mettere, riapriamo questa issue.
