### ISSUE TITLE
Stampare messaggio all'interruzione del download invece della stacktrace

### ISSUE THREAD

**Issue by LukeSavefrogs** [CoffeeStraw/VVVVID-Downloader#11]
Ciao,
al fine di migliorare l'usabilità utente del programma ho pensato che si potrebbe stampare a video un **messaggio parlante** all'utente invece di una **stacktrace** quando si interrompe il programma facendo <kbd>CTRL</kbd> + <kbd>C</kbd>

### Lo stesso snippet prima e dopo:
**Prima:**
![image](https://user-images.githubusercontent.com/33452387/81553999-4d4cc900-9386-11ea-9e68-fe8ffb0bbadd.png)

**Dopo:**
![image](https://user-images.githubusercontent.com/33452387/81554472-24790380-9387-11ea-831c-b4802768447f.png)

Come vedi la stacktrace che occupava tutto lo schermo è stata sostituita da 

> [VVVVID-Downloader] **Errore - Download abortito dall'utente**

### Realizzazione e possibili spunti
Al momento dato che si tratta di una prova è un semplice `try..except` inserito nella if finale da cui viene lanciato il `main()`:  

![image](https://user-images.githubusercontent.com/33452387/81555524-044a4400-9389-11ea-9818-423ff428df5a.png)

Se tale blocco venisse integrato anche all'interno del ciclo per il **download** del video si potrebbe inoltre specificare nella Except una sequenza di "**pulizia**" del file **.part** del video che si stava scaricando al momento dell'**interruzione**. Ovviamente quest'ultima è solo un'idea che mi è venuta al momento della scrittura e non è importante in quanto i file .part vengono sostituiti di volta in volta... Ma era giusto per non lasciare una situazione "sporca" se l'utente decide di interrompere il download :)

**Comment by CoffeeStraw** [comment]
Ciao! Ottima idea quella di gestire meglio l'output dell'errore.
Da notare però che l'eccezione **KeyboardInterrupt** è poco robusta e [non gestisce tutte quante le casistiche di interruzione del processo](https://stackoverflow.com/questions/40775054/capturing-sigint-using-keyboardinterrupt-exception-works-in-terminal-not-in-scr/40785230#40785230).

Per gestirle tutte, basta specificare un **handler** per la signal **SIGINT** ([esempio](https://stackoverflow.com/questions/1112343/how-do-i-capture-sigint-in-python)), responsabile dell'arresto di un processo.

Inoltre, secondo me è sbagliato eliminare i file .part (che comunque sarebbe possibile facilmente mediante [l'opzione --no-part](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#filesystem-options)), in quanto consento di riprendere il download da un punto sicuro, risparmiandosi così di riscaricare il tutto da capo.

**Comment by LukeSavefrogs** [comment]
Ciao,
per quanto riguarda la chiusura del programma avevo pensato alla possibilità che lo script potesse essere killato con altri segnali.

Tuttavia l'obbiettivo dell'issue era di rendere chiaro all'utente "normale" che prova da CLI a terminare il programma effettuando un semplice <kbd>CTRL</kbd> + <kbd>C</kbd> che la stacktrace **non è un'errore del programma**, ma una conseguenza dell'averlo interrotto, e quindi non porta a conseguenze negative... 

Se viene inviato al programma un segnale di altro tipo ad esempio tramite **`kill`** in *NIX-Like o dal **Task Manager** di Windows è chiaro che l'intenzione dell'utente è i killare direttamente il processo in modo "forzato" e quindi ho pensato fosse meno importante :smile: 

Della serie "It's not a bug, it's a feature...  "

![image](https://user-images.githubusercontent.com/33452387/81758194-5c846180-94c1-11ea-9629-baf25a98b9da.png)

----
Ad ogni modo si potrebbe aggiungere un handler per i segnali `SIGINT` e `SIGTERM` (rispettivamente <kbd>CTRL</kbd> + <kbd>C</kbd> e il default per il `kill)` mentre ovviamente non c'è possibilità di intercettare il `SIGKILL` (aka `kill -9)`. Come viene proposto [in questa risposta](https://stackoverflow.com/a/24574672/8965861) o [qui](http://avi.im/blag/2016/sigterm-in-python/) si può triggerare la funzione `sys.exit()` quando il programma riceve un segnale di tipo `SIGTERM` mostrando quindi correttamente a schermo un messaggio "di addio".

Dimmi tu se ho dimenticato qualcosa o se ci sono errori :smiley: 

Ad ogni modo da quello che vedo dovrebbe rimanere comunque la catch per la `KeyboardInterrupt` perchè in caso contrario comparirebbe lo stesso dopo il messaggio

Proverò questa soluzione e posterò qui i risultati...

**Comment by LukeSavefrogs** [comment]
Per quanto riguarda i file .part hai ragione... Non sapevo venissero usati per riprendere al download successivo.

Comunque... Mi sono appena accorto che avevi già linkato la risposta di SO sull'handler per il SIGINT... Ti chiedo scusa ahah
Lascio comunque la parte del commento precedente così che mi puoi correggere se sbaglio

**Comment by CoffeeStraw** [comment]
Ma figurati!
Allora, per me andrebbe bene anche gestire separatamente la SIGTERM (o comunque potremmo gestire entrambe le signal con lo stesso handler).

Non sono sicuro di aver capito bene comunque quello che intendevi per:

> Ad ogni modo da quello che vedo dovrebbe rimanere comunque la catch per la KeyboardInterrupt perchè in caso contrario comparirebbe lo stesso dopo il messaggio

non verrebbe tutto quanto gestito dall'handler? Non sono sicurissimo perché in Python non l'ho mai fatto e non posso testare al momento, quindi nel caso correggimi pure!

**Comment by LukeSavefrogs** [comment]
Ho appena controllato e no, la `KeyboardInterrupt` viene gestita dall'handler per il SIGINT... Appena posso provo a killare da linux (in VM) un processo che gira con il codice di test qui sotto.

Ad ogni modo sembra funzionare e sarebbe un modo elegante di risolvere il problema

### Codice
```python
import signal
import sys
import time

def sigterm_handler(_signo, _stack_frame):
    print("[Interrupt Handler] Received signal n° " + str(_signo))
    # Raises SystemExit(0):
    sys.exit(0)

signal.signal(signal.SIGTERM, sigterm_handler)
signal.signal(signal.SIGINT, sigterm_handler)

for ciclo in range(1, 50):
    print("Ciclo n° " + str(ciclo))
    time.sleep(1)
    pass
```

### Test
- Interrompendo lo script con <kbd>CTRL</kbd> + <kbd>C</kbd>:

   ![image](https://user-images.githubusercontent.com/33452387/81986779-c3785680-9638-11ea-86fd-6f7600b033be.png)

- Interrompendo lo script con il comando `kill`:
   
    _**Ancora da provare**_

**Comment by CoffeeStraw** [comment]
Ottimo! Sì, è decisamente il modo migliore secondo me. Dovrebbe andare anche col comando kill.
