### ISSUE TITLE
Aggiungere possibilità di scelta percorso di Output

### ISSUE THREAD

**Issue by LukeSavefrogs** [CoffeeStraw/VVVVID-Downloader#13]
Sarebbe molto interessante e utile dare la possibilità all'utente di poter **scegliere** (opzionalmente) la **cartella di output** in cui verranno create le cartelle degli episodi (se sta scaricando partendo da un link di una pagina con lista degli episodi). 

Questo farà in modo che non debba spostare tutte le serie scaricate nella cartella personale una volta terminati i download...

Se **non viene specificata** verrà usata quella di **default** (cioè nella cartella dello script dentro "Downloads/")...

Pensavo a qualcosa del genere:
![image](https://user-images.githubusercontent.com/33452387/81553640-bed84780-9385-11ea-83da-02fcc5b0c441.png)

---
### Realizzazione
Ho utilizzato il pacchetto `argparse`, inizializzandolo con i parametri `-o` (per il cambio di directory di output) e `-h` (per l'aiuto).

All'inizio dello script ho aggiunto la **import** del parser:
```python
import argparse
```
Poi ho raggruppato l'**inizializzazione** del parser dentro una **funzione**:
```python
# Using the package argparse, adds an ArgumentParser and help (try `python main.py -h` or `python main.py --help`)
def addArgumentParser():
	global dl_dir
	parser = argparse.ArgumentParser(
		prog='VVVVID-Downloader', 
		description='Un piccolo script in Python3 per scaricare contenuti multimediali (non a pagamento) offerti da VVVVID. ' +
					'Inserisci i link degli episodi che vuoi scaricare (episodio singolo o serie) nel file \'downloads_list.txt\'',
		epilog='Homepage del progetto: https://github.com/CoffeeStraw/VVVVID-Downloader',
		add_help=False
	)
	parser.add_argument(
		'-o', 
		'--output-directory', 
		type=str, 
		dest='output_dir',
		help='Definisce la cartella di output (default=' + dl_dir + ')'
	)
	parser.add_argument(
		'-h', 
		'--help', 
		action='help',
		help='Mostra questa schermata di aiuto ed esce'
	)
	args = parser.parse_args()

	if args.output_dir and args.output_dir.strip() != "":
		dl_dir = args.output_dir.strip()
		print("[VVVVID-Downloader] %sCambiata directory di output%s: %s" % (
				Fore.GREEN,
				Style.RESET_ALL,
				dl_dir
			)
		)
```
Poi, nella funzione `main()` **richiamo** la funzione `addArgumentParser()`: 
```python
def main():
	# Getting Colorama utility ready to work
	colorama_init(autoreset=True)

	# Checks if there are special parameters passed to the script (-h/-o)
	addArgumentParser()
```

**Comment by CoffeeStraw** [comment]
Già che ci siamo si potrebbe implementare anche un altro parametro...
In riassunto:
- `i`: specifica il file di input .txt;
- `o`: specifica il percorso (relativo o assoluto) per la cartella che conterrà gli output (vanno fatti controlli sul fatto che il percorso esista e sia valido);

Inoltre, lo script potrebbe accettare una sequenza di 0 o più link direttamente da riga di comando (indipendenti quindi dai comandi di argparse). Se vengono passati dei link, il programma non analizzerà più il file .txt. Se non viene passato neanche un link, né viene utilizzato il comando `-i`, il programma potrebbe assumere come comportamento di default quello con cui ha sempre lavorato finora: analizza il file `downloads_list.txt` (se esiste) e salva ogni cosa scaricata all'interno della cartella `Downloads`...

Che ne dici?

**Comment by CoffeeStraw** [comment]
Come va con questa issue? Fai pure una PR quando pensi di esserci, così revisiono tutto e nel caso propongo modifiche sulla tua fork.

**Comment by LukeSavefrogs** [comment]
Che ne pensi se invece di chiamare il flag per il file dei link `-i` non lo indichiamo come `-f` per renderlo conforme allo stile *NIX dei comandi dove il `-f` indica spesso un file esterno da dare in pasto al programma?

Per quanto riguarda la **cartella di output** lo script al momento la crea se non esiste. Pensi possa essere un comportamento pericoloso in caso si mettano percorsi particolari?

**Comment by CoffeeStraw** [comment]
Sono d'accordo col cambiare da `-i` a `-f`, meglio ed è comunque intuitivo.

Per quanto riguarda la cartella di output, l'utilizzo sicuro del comando spetta all'utente, nella mia esperienza non ho mai visto fare controlli particolari prima di creare una cartella non esistente. E al limite l'impossibilità di creare la cartella per una qualche ragione x (come caratteri non validi per il suo nome) credo vengano segnalate con un errore, anche se sulla [documentazione ufficiale](https://docs.python.org/3/library/os.html#os.mkdir) non leggo nulla a riguardo. Si potrebbe pensare invece di utilizzare [makedirs](https://docs.python.org/3/library/os.html#os.makedirs), ma credo sia più safe utilizzare mkdir. Es:
- Path desiderato: `D:\User\Bla\Bla\Desktop`;
- L'utente digita male e scrive: `D:\Usr\Bla\Bla\Desktop`;
- L'utente non riceve nessun errore e non si trova la cartella dove desiderava.

**Comment by CoffeeStraw** [comment]
Ci ho lavorato nell'ultimo commit e dovrei aver risolto! Nel caso ci sono problemi apri pure una nuova issue!
