### ISSUE TITLE
Download automatico di ffmpeg

### ISSUE THREAD

**Issue by CoffeeStraw** [CoffeeStraw/VVVVID-Downloader#15]
Ho pensato che si potrebbe migliorare la prima esperienza con lo script evitando all'utente di recuperarsi da solo ffmpeg, se non trovato.

**Comment by marcospampi** [comment]
Magari puoi avvalerti delle release, con due opzioni di download tra solo script e script+ffmpeg, così non ti complichi la vita

**Comment by CoffeeStraw** [comment]
Potrei farlo, magari solo per gli utenti Windows visto che per gli altri OS ffmpeg è facilmente installabile con un comando da cmd. Grazie dell'idea!

**Comment by marcospampi** [comment]
Dalla bash!!1!!1! 😂
Di niente 👍

**Comment by CoffeeStraw** [comment]
Con il commit ca41683 ffmpeg non è più una dipendenza per poter scaricare da VVVVID, per cui chiudo la issue.
