### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by fl4me11** [CoffeeStraw/VVVVID-Downloader#16]
Traceback (most recent call last):
  File "main.py", line 203, in <module>
    main()
  File "main.py", line 199, in main
    dl_from_vvvvid(line, requests_obj, ffmpeg_local)
  File "main.py", line 53, in dl_from_vvvvid
    dl_dir, os_fix_filename(cont_title + " - " + season["name"])
  File "/home/fl4me/VVVVID-Downloader/text_utility.py", line 17, in os_fix_filename
    return re_sub(r"[\/]+", "\\", filename)
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 325, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.8/re.py", line 316, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.8/sre_parse.py", line 972, in parse_template
    s = Tokenizer(source)
  File "/usr/lib/python3.8/sre_parse.py", line 232, in __init__
    self.__next()
  File "/usr/lib/python3.8/sre_parse.py", line 245, in __next
    raise error("bad escape (end of pattern)",
re.error: bad escape (end of pattern) at position 0

**Comment by LukeSavefrogs** [comment]
Ciao,

Potresti fornire più informazioni? 
Ad esempio: 
- Che serie o episodio stavi scaricando? 
- Quando ha dato l'errore? Immediatamente o dopo un pochino?
- Puoi postare il messaggio completo da quando lanci `python main.py` a quando si blocca il programma?

**Comment by CoffeeStraw** [comment]
Sei sicuro di avere l'ultima versione? Dal log che hai postato leggo:

> File "/home/fl4me/VVVVID-Downloader/text_utility.py", line 17, in os_fix_filename
return re_sub(r"[/]+", "\", filename)

Mentre la riga 17 del file text_utility è:
https://github.com/CoffeeStraw/VVVVID-Downloader/blob/9e925e7e8387fd4fec71e11837907514b798b03e/text_utility.py#L17

**Comment by LukeSavefrogs** [comment]
> Sei sicuro di avere l'ultima versione? Dal log che hai postato leggo:
> 
> > File "/home/fl4me/VVVVID-Downloader/text_utility.py", line 17, in os_fix_filename
> > return re_sub(r"[/]+", "\", filename)
> 
> Mentre la riga 17 del file text_utility è:
> https://github.com/CoffeeStraw/VVVVID-Downloader/blob/9e925e7e8387fd4fec71e11837907514b798b03e/text_utility.py#L17
> 
> È strano, ti ha levato di mezzo il singolo `\`...

Già... Ho notato anche io... Strano

**Comment by CoffeeStraw** [comment]
Ho appena risolto, grazie della segnalazione @fl4me11!

In realtà non aveva tolto il singolo `\`, solo che l'utente aveva semplicemente copiato il log e quindi GitHub ha interpretato alcune cose (tra cui lo `\`) in maniera sbagliata.

Il problema comunque nasceva dalla stringa di sostituzione `"\\"`, veniva interpretata male e mi è bastato indicare a Python di trattarla come raw-string per risolvere!

**Comment by LukeSavefrogs** [comment]
Quindi si tratta solo di una commit vecchia?

Uhmm... Che ne pensi di integrare un sistema di versioning? All'avvio lo script potrebbe stampare la propria versione e sarebbe più semplice capire che versione ha l'utente

Inoltre si potrebbe fare che passando da linea di comando un parametro stile `-V|--version` ti stampi a video la versione dello script

**Comment by xfl4me** [comment]
> Ciao,
> 
> Potresti fornire più informazioni?
> Ad esempio:
> 
> * Che serie o episodio stavi scaricando?
> * Quando ha dato l'errore? Immediatamente o dopo un pochino?
> * Puoi postare il messaggio completo da quando lanci `python main.py` a quando si blocca il programma?

Succede subito, e stavo cercando di scaricare Attack on Titan.
Quello che ho postato è il log intero

**Comment by xfl4me** [comment]
> Ho appena risolto, grazie della segnalazione @fl4me11!
> 
> In realtà non aveva tolto il singolo `\` @LukeSavefrogs, solo che l'utente aveva semplicemente copiato il log e quindi GitHub ha interpretato alcune cose (tra cui lo `\`) in maniera sbagliata.
> 
> Il problema comunque nasceva dalla stringa di sostituzione `"\\"`, veniva interpretata male e mi è bastato indicare a Python di trattarla come raw-string per risolvere!

Va bene, quindi è già usabile?

**Comment by CoffeeStraw** [comment]
> > Ho appena risolto, grazie della segnalazione @fl4me11!
> > In realtà non aveva tolto il singolo `\` @LukeSavefrogs, solo che l'utente aveva semplicemente copiato il log e quindi GitHub ha interpretato alcune cose (tra cui lo `\`) in maniera sbagliata.
> > Il problema comunque nasceva dalla stringa di sostituzione `"\\"`, veniva interpretata male e mi è bastato indicare a Python di trattarla come raw-string per risolvere!
> 
> Va bene, quindi è già usabile?

Sì, ti basta riscaricare il programma ed è tutto risolto! Grazie ancora, ho imparato un'altra cosa oggi 😄

**Comment by CoffeeStraw** [comment]
> Quindi si tratta solo di una commit vecchia?
> 
> Uhmm... Che ne pensi di integrare un sistema di versioning? All'avvio lo script potrebbe stampare la propria versione e sarebbe più semplice capire che versione ha l'utente
> 
> Inoltre si potrebbe fare che passando da linea di comando un parametro stile `-V|--version` ti stampi a video la versione dello script

Ci stavo pensando in effetti, poi pensavo di rendere lo script un module installabile con pip per rendere lo script chiamabile ovunque nel sistema... Però devo valutare bene appena ho tempo e poi butto giù la proposta in una issue @LukeSavefrogs
