### ISSUE TITLE
Errore in Windows 10 e Python 3.9.0

### ISSUE THREAD

**Issue by marcoguastalli** [CoffeeStraw/VVVVID-Downloader#18]
Hola, mi da questo errore in WIndows 10 con Python 3.9.0:

python main.py

Traceback (most recent call last):
  File "C:\opt\VVVVID-Downloader\main.py", line 205, in <module>
    main()
  File "C:\opt\VVVVID-Downloader\main.py", line 157, in main
    "conn_id": current_session.get(
  File "C:\Users\winzozz\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by simoneghirardin** [comment]
Ciao, anch'io ho lo stesso problema. Ho provato a stampare il risultato della current_session.get e mi da <Response [403]>(naturalmente ho tolto il # nel file dei link).
VVVVID per caso ha imposto qualche blocco?

**Comment by CoffeeStraw** [comment]
Salve, scusatemi per il ritardo nella risposta a questa issue, in giornata cerco di fare qualche prova e sistemare quell'errore (non dovrebbe essere complesso da sistemare).

Nel mentre @simoneghirardin potresti passarmi uno dei link che hai provato?

**Comment by simoneghirardin** [comment]
https://www.vvvvid.it/show/1414/l-attacco-dei-giganti-la-stagione-finale. Ho provato anche questo nel caso https://www.vvvvid.it/show/114/l-attacco-dei-giganti. Entrambi non funzionano. Grazie.

**Comment by CoffeeStraw** [comment]
@simoneghirardin ho provato sia con il primo che con il secondo link, ma lo script pare funzionare ancora. Però io ho utilizzato Python 3.9.1 (che è la ultima versione disponibile) e, per stare sicuro, ho rilanciato il comando `pip install -r requirements.txt` per aggiornare alcune dipendenze.

Potresti provare a fare altrettanto e vedere se riesci a risolvere? Grazie!

**Comment by CoffeeStraw** [comment]
Non appena mi dai conferma che tutto funziona provvederò a chiudere questa issue.

**Comment by str3gatto** [comment]
Aggiornato python all'ultima versione, installato tutte le dipendenze, torna ancora lo stesso errore.

```
Nota Bene: siccome lo script è stato lanciato da Windows i nomi delle cartelle e dei file potrebbero subire delle variazioni.

Traceback (most recent call last):
  File "C:\Users\main\Desktop\VVVVID-Downloader-master\main.py", line 205, in <module>
    main()
  File "C:\Users\main\Desktop\VVVVID-Downloader-master\main.py", line 157, in main
    "conn_id": current_session.get(
  File "C:\Users\main\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\main\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\main\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\main\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

Non solo con quei titoli ma anche con altri.

**Comment by CoffeeStraw** [comment]
Ciao, a me andava, ma effettivamente anche a me ora non va, ma credo di aver capito il perché:
https://www.vvvvid.it/
![image](https://user-images.githubusercontent.com/16942527/102021412-eeb65600-3d7f-11eb-929b-7b8cf5795e60.png)

Il sito non è raggiungibile, l'errore andrebbe segnalato comunque un po' meglio. Provvederò! (Puoi confermare che è questo l'errore riprovando non appena è raggiungibile?)

**Comment by str3gatto** [comment]
non avevo notato, se necessario aggiorno il funzionamento del tool appena possibile qui sotto, grazie del supporto

**Comment by CoffeeStraw** [comment]
Di niente. In realtà ho appena aggiornato il tool, provvedo a pushare le modifiche!

**Comment by simoneghirardin** [comment]
ieri sera non era in manutenzione e sto usando la versione 3.9.1. Ho anche lanciato pip install -r requirements.txt. Grazie del supporto

**Comment by CoffeeStraw** [comment]
Questo è un errore diverso da quello che scappava fuori a me. A me l'html restituito conteneva "error".

Probabilmente sì, è dovuto al proxy che stai usando. Se riusciamo a capire che il problema è dato veramente da solo questo, lo riporto nel readme per chiarezza.

**Comment by CoffeeStraw** [comment]
Dalla pagina Facebook di VVVVID:
`Per motivi di copyright VVVVID non è disponibile all'estero, in quanto i diritti che abbiamo acquistato per lo streaming dei contenuti riguardano solo il territorio italiano. Per questo per accedere alla piattaforma è necessario possedere un indirizzo IP italiano.`

**Comment by str3gatto** [comment]
funziona tutto

**Comment by CoffeeStraw** [comment]
Perfetto ragazzi, ho anche provveduto a specificare l'uso di un indirizzo IP italiano nel readme. Chiudo la Issue siccome mi sembra che sia tutto risolto ora, grazie a tutti della collaborazione!
