### ISSUE TITLE
Includere le funzionalità di questo script in youtube-dl

### ISSUE THREAD

**Issue by pjammo** [CoffeeStraw/VVVVID-Downloader#20]
L'extractor di youtube-dl non è aggiornato da diverso tempo e non include alcune funzioni che questo script invece ha, come la gestione delle playlist.
Ci sarebbe la possibilità di portarle?

Issue di riferimento: [#18130](https://github.com/ytdl-org/youtube-dl/issues/18130)

**Comment by CoffeeStraw** [comment]
Ciao! Avendo buttato un occhio a come youtube-dl gestisce il supporto ai siti sì, sarebbe possibile anche se non in modo completo come quella di questo script.

Tieni inoltre presente che ci sono diversi vantaggi nell'avere un software dedicato, primo tra tutti la User Experience semplificata (poche opzioni, nominazione e categorizzazione automatica dei download ecc.), ma anche la flessibilità (non siamo vincolati al funzionamento di YouTube-DL per gli aggiornamenti, le PR per un progetto grande come il loro sono abbastanza lente nell'essere accettate).

Per cui sarebbe possibile portare la gestione delle playlist in YouTube-DL, ma al momento non ho il tempo di capire come integrare il codice al meglio (ho giusto dato un'occhiata rapida). Comunque, come motivato, il software VVVVID-Downloader verrà mantenuto. Terrò la issue aperta per ricordarmi di questa possibilità, grazie della segnalazione!

**Comment by pjammo** [comment]
Certo, capisco i vantaggi di un software dedicato.

Grazie a te, spero riuscirai a trovare il tempo per farlo. Sarebbe bello avere la possibilità di sfruttare la versatilità di youtube-dl.

**Comment by nixxo** [comment]
https://github.com/ytdl-org/youtube-dl/pull/27574

**Comment by nixxo** [comment]
fatto: https://github.com/ytdl-org/youtube-dl/pull/27618

**Comment by CoffeeStraw** [comment]
Mi fa molto piacere! Provvedo a chiudere la issue.
