### ISSUE TITLE
Istruzioni poco chiare

### ISSUE THREAD

**Issue by McTakeda** [CoffeeStraw/VVVVID-Downloader#22]
So che non si dovrebbe chiedere qui, ma che vuol dire "Scaricate l'ultima release da TODO"? Cos'è un sito? Se si non lo trovo. Non ho capito come dovrei scaricare il programma.

**Comment by CoffeeStraw** [comment]
Hai perfettamente ragione. L'idea era quella di automatizzare la produzione di file eseguibili e renderli disponibili ad ogni update del programma, ma ancora non è stata realizzata. Per questo, avevo temporaneamente scritto "TODO" (da fare).

Provvedo a fare un commit veloce per renderlo più chiaro. Grazie!
