### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by easly1989** [CoffeeStraw/VVVVID-Downloader#25]
Purtroppo anche questo downloader non funziona piu, a causa del pacchetto youtube-dl

`[VVVVID] Downloading JSON metadata
[VVVVID] 486288: Downloading JSON metadata
[VVVVID] 486288: Downloading JSON metadata
[VVVVID] 486288: Downloading f4m manifest
[VVVVID] 486288: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

purtroppo python non è proprio il mio campo,
spero tu riesca a risolvere

**Comment by CoffeeStraw** [comment]
Hai provato ad aggiornare il pacchetto? Magari hai una versione vecchia.
Lo fai con il comando (da terminale):
```pip install --upgrade youtube-dl```

**Comment by easly1989** [comment]
si ho provato, stesso errore
a te non capita?
io ho provato a scaricare The Office (da questo link https://www.vvvvid.it/show/393/the-office) e poi anche gli episodi singoli, l'errore è sempre lo stesso

Tra l'altro ho provato ad usare direttamente anche youtube-dl ed ho avuto lo stesso problema,
magari sto sbagliando io qualcosa eh

**Comment by CoffeeStraw** [comment]
No, non stai sbagliando niente.
Non so cosa abbia di diverso questa serie, ma youtube-dl fallisce (per cui anche il mio script). Infatti se lo provi ad usare con qualche anime (io finora ho scaricato solo quelli da VVVVID), funziona tutto come dovrebbe.

Aprirò una issue su youtube-dl.

**Comment by CoffeeStraw** [comment]
L'ho aperta, puoi seguire lo sviluppo della issue su: https://github.com/ytdl-org/youtube-dl/issues/28473

**Comment by CoffeeStraw** [comment]
A quanto pare hanno [già risolto](https://github.com/ytdl-org/youtube-dl/commit/fa6bf0a7112e83d36567072985d56440bb34de72), ora bisogna aspettare che facciano una nuova release. Ti tengo aggiornato.

**Comment by easly1989** [comment]
ottimo!
Perfetto, grazie mille @CoffeeStraw  :)

**Comment by CoffeeStraw** [comment]
La issue si può considerare risolta, oggi gli sviluppatori di youtube-dl hanno rilasciato la nuova versione contenente il fix per vvvvid. Ho provveduto quindi anche io a rilasciare una nuova release che potrai sfruttare se sei su Windows.
