### ISSUE TITLE
Video Corrotti

### ISSUE THREAD

**Issue by baszin** [CoffeeStraw/VVVVID-Downloader#27]
Possiedo un Windows 10 con architettura a 64 bit e Pyhon 3.9. 
Ho usato lo script per scaricare gli episodi di Attack On Titan, tutto a posto tranne per il primo episodio, il quale video aveva varie sgranature.
Successivamente ho scaricato la seconda stagione e vari episodi in un certo punto hanno l'audio e il video non sincronizzato, tuttavia su VVVVID non ci sono problemi. Come potrei risolvere?

**Comment by CoffeeStraw** [comment]
Ciao, grazie per la segnalazione! È un bug che ho riscontrato anche io ed è dovuto all'uso di HLS Native per scaricare gli episodi, che a quanto pare è un po' instabile.

Sono al lavoro per abbandonare l'uso di youtube-dl (che fa uso di HLS Native) per scaricare gli episodi, delegando invece il download direttamente ad ffmpeg.

**Comment by CoffeeStraw** [comment]
Siccome sei su Windows, puoi anche provare la nuova release che ho pubblicato.
