### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by urfausto** [CoffeeStraw/VVVVID-Downloader#30]
l'ultima versione non può girare su windows 7 perchè python 3.9 richiede windows 10

![Senza nome](https://user-images.githubusercontent.com/31393590/115151240-55b88400-a06c-11eb-89a5-07e7186a08a6.png)

**Comment by urfausto** [comment]
non puoi usare la versione 3.8.8 per favore?  :crying_cat_face:

**Comment by CoffeeStraw** [comment]
Ciao, scusa il ritardo, vedo che si può fare, al momento non ho in mente un modo comodo dal momento che ho installato solo Python 3.9

**Comment by CoffeeStraw** [comment]
Tieni comunque in considerazione la possibilità di installare Python 3.8 ed eseguire direttamente lo script, piuttosto che avvalerti del .exe che ho prodotto.

**Comment by urfausto** [comment]
> Tieni comunque in considerazione la possibilità di installare Python 3.8 ed eseguire direttamente lo script, piuttosto che avvalerti del .exe che ho prodotto.

ok mi puoi dire come fare questo? avevo già usato una versione iniziale ma ora non mi ricordo più come si fa e qui non ci sono le istruzioni complete, su youtube non c'è più il video.

**Comment by CoffeeStraw** [comment]
Ho prodotto una nuova release e sono passato ad usare Python 3.8, puoi farmi sapere come va?
https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.0

Grazie!

**Comment by CoffeeStraw** [comment]
Ho appena pubblicato una nuova release, che da ora in poi (fin quando sarà possibile) produrrò in Python 3.8. Potresti provare a vedere come va?
https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.1

**Comment by urfausto** [comment]
> Ho appena pubblicato una nuova release, che da ora in poi (fin quando sarà possibile) produrrò in Python 3.8. Potresti provare a vedere come va?
> https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.1

ok, la provo subito. comunque mi rendo conto solo ora che si può usare python fino alla versione **3.8.9** su windows 7.

**Comment by urfausto** [comment]
provato e funziona a meraviglia.
in questo caso, anche se non mi interessava però, un extra (trailer) non l'ha scaricato dalla serie con cui ho provato: ha solo creato la cartella degli extra e dopo ha avuto un errore.

**Comment by CoffeeStraw** [comment]
Potresti aprire un'altra issue a riguardo? Sarei interessato ad approfondire meglio l'errore. Grazie!
