### ISSUE TITLE
Download bloccati

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#32]
Ciao,

allego screen del problema:
![2021-05-01_214827](https://user-images.githubusercontent.com/7345587/116793436-09872e00-aac7-11eb-8f38-47de555cf437.png)

Come vedi il download si è bloccato a 121MB e non continua.
Prima ho dovuto chiudere visto che si era bloccato a metà dell'episodio 5.
Posso mandarti qualche log? non mi sembra che l'applicazione li generi

**Comment by CoffeeStraw** [comment]
Ciao, grazie per la segnalazione!
Innanzitutto verifica di star usando l'ultima versione. Dopodichè potrebbe aiutarmi sapere se ti capita spesso e se la tua connessione è instabile.

Al momento comunque non è possibile generare alcun log, però è una buona idea e lo permetterò quanto prima.

**Comment by Bazzu85** [comment]
Ciao,
rispondo per punti..

1. ho scaricato lo script ieri sera, versione windows. quindi 1.4.2
2. mi capita spesso ma non a intervalli definiti.
3. ho provato sia usando il bat che usando il main.exe, dopo un po i download si bloccano
4. se vuoi possiamo sentirci privatamente per una sessione di debug
grazie

**Comment by Bazzu85** [comment]
Mi sono accorto cmq che scaricando 
https://www.vvvvid.it/show/1414/l-attacco-dei-giganti-la-stagione-finale
ad un certo punto prova a scaricare LIVE con Giò.
Guardando le release nella 1.2 dovresti aver tolto la funzionalità, ma io ho scaricato la 1.4.2
https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.2

**Comment by CoffeeStraw** [comment]
> Ciao,
> rispondo per punti..
> 
> 1. ho scaricato lo script ieri sera, versione windows. quindi 1.4.2
> 2. mi capita spesso ma non a intervalli definiti.
> 3. ho provato sia usando il bat che usando il main.exe, dopo un po i download si bloccano
> 4. se vuoi possiamo sentirci privatamente per una sessione di debug
>    grazie

Credo che per ora sarebbe sufficiente avere un po' più dettagli su cosa accade durante il download. Lavorerò ad una modalità verbosa ed appena sarà pronta te lo farò sapere qui.

**Comment by CoffeeStraw** [comment]
Oh già, una cosa importante che mi sono scordato di chiederti:

> Mi sono accorto cmq che scaricando
> https://www.vvvvid.it/show/1414/l-attacco-dei-giganti-la-stagione-finale
> ad un certo punto prova a scaricare LIVE con Giò.
> Guardando le release nella 1.2 dovresti aver tolto la funzionalità, ma io ho scaricato la 1.4.2
> https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.2

Forse non sono stato molto chiaro nel changelog. Gli episodi "live registrati" che vengono caricati su vvvvid e quindi figurano come "episodio" verranno sempre e comunque scaricati. Il downloader eviterà però di tentare di scaricare eventuali "live in corso".

**Comment by Bazzu85** [comment]
> > Ciao,
> > rispondo per punti..
> > 
> > 1. ho scaricato lo script ieri sera, versione windows. quindi 1.4.2
> > 2. mi capita spesso ma non a intervalli definiti.
> > 3. ho provato sia usando il bat che usando il main.exe, dopo un po i download si bloccano
> > 4. se vuoi possiamo sentirci privatamente per una sessione di debug
> >    grazie
> 
> Credo che per ora sarebbe sufficiente avere un po' più dettagli su cosa accade durante il download. Lavorerò ad una modalità verbosa ed appena sarà pronta te lo farò sapere qui.

ok!
grazie!

**Comment by Bazzu85** [comment]
> > Mi sono accorto cmq che scaricando
> > https://www.vvvvid.it/show/1414/l-attacco-dei-giganti-la-stagione-finale
> > ad un certo punto prova a scaricare LIVE con Giò.
> > Guardando le release nella 1.2 dovresti aver tolto la funzionalità, ma io ho scaricato la 1.4.2
> > https://github.com/CoffeeStraw/VVVVID-Downloader/releases/tag/v1.4.2
> 
> Forse non sono stato molto chiaro nel changelog. Gli episodi "live registrati" che vengono caricati su vvvvid e quindi figurano come "episodio" verranno sempre e comunque scaricati. Il downloader eviterà però di tentare di scaricare eventuali "live in corso".

avevo capito male io allora! 
ora è chiaro!

**Comment by CoffeeStraw** [comment]
Ho appena pubblicato una nuova versione che aggiunge, tra le altre opzioni, una modalità verbose che possiamo utilizzare per ottenere qualche informazione in più sul download.

Per usarla è sufficiente che modifiche il .bat nella release, sostituendo la riga
`main.exe`
in
`main.exe -v`.

Appena ti capita un file che ti si blocca ed hai l'output verboso postalo pure qui.

**Comment by Bazzu85** [comment]
Ecco: https://pastebin.com/5eFB2aTt

non vedo errori..si blocca in questo caso al segmento 121.
Chiudendo, cancellando il file temp, ripartendo.. il file si scarica ok ma si blocca su uno dei successivi..

**Comment by CoffeeStraw** [comment]
La mia ipotesi è che per un qualche motivo perdi la connessione e ffmpeg si blocca. Sto provando a cercare online una soluzione.

**Comment by CoffeeStraw** [comment]
A quanto pare è proprio una gestione non corretta da parte di ffmpeg:
https://trac.ffmpeg.org/ticket/6724

C'è un ticket aperto, ma è lì da 4 anni... Comunque a quanto pare dipende proprio dalla tua connessione, anche se non saprei darti i dettagli. Per il momento lascio aperta la issue, caso mai dovessi trovare una qualche soluzione alternativa.

**Comment by CoffeeStraw** [comment]
Visto che ho constatato di non avere modo di risolvere questo problema, per il momento chiudo la issue. Se dovessero uscire fuori delle soluzioni sono disponibile a riaprirla.
