### ISSUE TITLE
Serie in errore

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#33]
Ciao,

per la serie:
https://www.vvvvid.it/show/86/alexander-cronache-di-guerra-di-alessandro-il-grande
lo script dice questo:

`In preparazione: Alexander: Cronache Di Guerra Di Alessandro Il Grande
Descrizione:     Macedonia, 356 a.C. La regina Olimpiade, sacerdotessa di un oscuro culto votato all'apocalisse, dà alla luce un erede maschio al consorte Filippo II. Sul futuro di quel bambino grava però una tremenda profezia: un giorno egli sarà responsabile della distruzione del mondo. Tra congiure di palazzo e dissidi famigliari, il giovane principe Alessandro, futuro dominatore del mondo, si troverà ad affrontare il dilemma fondamentale della sua esistenza: conquistare per distruggere, come vorrebbe sua madre, o conquistare per governare, come vorrebbe il suo maestro Aristotele? Fine o inizio? Ordine o caos?

Stagione: Episodi
- Episodio 01: La nascita del distruttore del mondo in download
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "main.py", line 209, in <module>
  File "main.py", line 195, in main
  File "main.py", line 107, in dl_from_vvvvid
KeyError: 'url'
[14024] Failed to execute script main
Press any key to continue . . .`

ovviamente il link è corretto
grazie

**Comment by CoffeeStraw** [comment]
Dovrei aver corretto con l'ultimo commit, se puoi scaricare la versione e darmi un feedback potrebbe essermi comodo!
E grazie ancora per la segnalazione!

**Comment by Bazzu85** [comment]
Ok, sembra andare..
ti ricordo che abbiamo ancora in sospeso https://github.com/CoffeeStraw/VVVVID-Downloader/issues/32

grazie mille!
