### ISSUE TITLE
Film in errore

### ISSUE THREAD

**Issue by GioMari2006** [CoffeeStraw/VVVVID-Downloader#34]
Ciao, ho provato ad installare vari film ma tutto quello che mi dice è questo:
NOTA BENE: siccome lo script è stato lanciato da Windows i nomi delle cartelle e dei file creati potrebbero subire delle variazioni.

In preparazione: Weathering With You
Descrizione:     L’estate del primo anno di liceo, Hodaka decide di fuggire. Scappa dalla sua remota isola natale per cercare fortuna a Tokyo. Qui Hodaka deve farcela con pochi soldi in tasca e qualche problema personale. Finché non incontra Hina, una ragazza brillante ed energica che possiede un’abilità meravigliosa: il potere di fermare la pioggia e far risplendere il sole!

Stagione: FILM
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
- Episodio 01: Weathering With You in download
Traceback (most recent call last):
  File "main.py", line 224, in <module>
  File "main.py", line 210, in main
  File "main.py", line 127, in dl_from_vvvvid
FileNotFoundError: [WinError 2] Impossibile trovare il file specificato: 'C:\\Users\\User\\Documents\\VVVVID Downloader\\Downloads\\Weathering With You - FILM\\01 - Weathering With You.part.mkv' -> 'C:\\Users\\User\\Documents\\VVVVID Downloader\\Downloads\\Weathering With You - FILM\\01 - Weathering With You.mkv'
[61924] Failed to execute script main
Premere un tasto per continuare . . .

**Comment by CoffeeStraw** [comment]
Ciao. Come indicato in descrizione, non è possibile scaricare alcun contenuto a pagamento tramite questo software. Provvederò a fornire un messaggio di errore nel software per segnalarlo.
