### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#35]
Ciao,
oggi mi è capitato questo errore:
https://pastebin.com/ExJ8n7n5

Facendo ripartire il bat prosegue da dove aveva lasciato..

**Comment by CoffeeStraw** [comment]
Ho pushato una nuova versione che dovrebbe risolvere il problema. Per il momento chiudo la issue, ma se dovessero capitare nuovamente problemi simili, non farti problemi ad aprirne una nuova! Grazie ancora!
