### ISSUE TITLE
Download incompleti considerati come completi

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#36]
Ciao,

come da titolo...
se chiudi l'app a metà download, il file generato viene considerato come ok per i successivi avvii..

non si potrebbe fare in modo di mettere nella cartella finale solo i file effettivamente scaricati al 100%?
altrimenti ad ogni avvio devi andare a cancellare a mano i file incompleti

**Comment by CoffeeStraw** [comment]
Ciao! Grazie della segnalazione, in realtà il caso è già gestito: i file non completati hanno estensione ".part.mkv". Stranamente però, se chiudo il bat (e non fermo la sua esecuzione con CTRL+C), l'estensione del file scaricato viene cambiata in ".mkv" anche se il download non è terminato (invece, la ridenominazione dovrebbe avvenire solo a download completamente scaricato).

Indagherò!

**Comment by Bazzu85** [comment]
si l'ho notato..
una possibile soluzione sarebbe di scaricare sempre in una cartella Temp (sempre dentro Downloads) e poi a download finito spostare il file nella cartella appropriata..

**Comment by CoffeeStraw** [comment]
Ho pushato una nuova versione che dovrebbe risolvere il problema. Potresti provare? Grazie!

**Comment by Bazzu85** [comment]
ok, sembra funzionare...
ti aggiorno qui se riscontro di nuovo il problema, grazie
