### ISSUE TITLE
ERROR: Sign in to confirm your age

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#37]
Ciao,
altro errore da fixare secondo me:
https://pastebin.com/kgVJ6rBt

grazie

**Comment by CoffeeStraw** [comment]
Grazie ancora una volta per la segnalazione. Non ho modo di risolvere il problema totalmente (in quanto alcuni video sono esterni a vvvvid e sono presi da YouTube, che per alcuni video pone dei limiti sull'età), ma almeno ora il programma non dovrebbe andare più in crash.

**Comment by Bazzu85** [comment]
Figurati...penso cmq di riuscire domani a testare.

Grazie a te per il programma.. veramente utilissimo!
Giusto per aggiornarti ultimamente capita sempre meno che i download si blocchino (problema di ffmpeg). Può essere che si sia sistemata la connessione oppure l'ultimo aggiornamento dei driver ethernet che ho trovato..
Grazia ancora
