### ISSUE TITLE
Episodi con problemi all'audio

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#39]
Ciao,

ogni episodio che viene scaricato devo sempre controllare che non abbia problemi all'audio..
ti posso fornire privatamente un episodio che si è scaricato con:
- fino a 9.30 tutto ok
- dopo comincia a esserci uno sfasamento dell'audio
- ad un certo punto piu niente

riscaricando la puntata tutto ok
ora cerco di scaricare di nuovo la stagione con il debug e vedo poi se qualche episodio si è scaricato con problemi..

**Comment by CoffeeStraw** [comment]
Ciao!
Avevo già tentato in passato di lavorare a questo errore, ma purtroppo ci sono dei problemi con FFMpeg.
Per ora lascio aperta la issue per ricordarmi di ri-effettuare un controllo, ma non penso si possa fare altro. Grazie della segnalazione.

**Comment by Bazzu85** [comment]
ok, quindi il metodo migliore è controllare puntata per puntata se a fine file c'è l'audio ed è in sync!

**Comment by CoffeeStraw** [comment]
> ok, quindi il metodo migliore è controllare puntata per puntata se a fine file c'è l'audio ed è in sync!

Purtroppo fino a quando non fixano sì... Considera che con ogni nuova release che faccio, viene anche presa e inserita l'ultima versione di FFMpeg, quindi magari la issue si risolverà col tempo da sola. Per il momento chiudo.
