### ISSUE TITLE
Il downloader non funziona

### ISSUE THREAD

**Issue by Xenuss** [CoffeeStraw/VVVVID-Downloader#4]
Ciao,
all'avvio il downloader funziona come dovrebbe, ma nel momento in cui si appresta a scaricare il file da vvvvid da questo errore

Saluti

![2020-01-11 211614](https://user-images.githubusercontent.com/59777197/72210167-9f084400-34b7-11ea-8cc6-1758a5ff227d.png)

**Comment by CoffeeStraw** [comment]
Ciao, potresti condividere l'URL da cui stai tentando di scaricare così da poter provare a replicare l'errore?

**Comment by Xenuss** [comment]
Ecco, è questo
https://www.vvvvid.it/show/897/my-hero-academia-quarta-stagione

**Comment by CoffeeStraw** [comment]
Dovrei aver risolto, prova ad aggiornare lo script e riprova :)

**Comment by Xenuss** [comment]
Ok, domattina appena accendo il PC controllo 
Grazie mille!
