### ISSUE TITLE
Il server ha rifiutato l'accesso al file

### ISSUE THREAD

**Issue by Bazzu85** [CoffeeStraw/VVVVID-Downloader#48]
Ciao,

ho questo errore 
- Episodio 13: Sorpresa al circo in download
[ERROR] Il server ha rifiutato l'accesso al file. Si ricorda che con il presente software non è possibile scaricare contenuti a pagamento. Se pensi si tratti di un errore, puoi aprire una issue su GitHub.

non solo su questo file ma anche sugli altri dello stesso link che riporto:
https://www.vvvvid.it/show/706/yu-gi-oh-arc-v

Potete aiutarmi?

edit: anche per altri link, sembra che il problema sia generalizzato
sto usando l'ultima versione presa da qui

**Comment by Bazzu85** [comment]
Ecco qua il lancio con verbose e alcuni errori:
https://gist.github.com/Bazzu85/78b43410b75d18bfefb6d609f20a6a97

**Comment by CoffeeStraw** [comment]
Dovrei aver risolto con l'ultimo commit, a breve dovrebbe uscire la nuova versione. Non appena è disponibile potresti verificare che funziona come dovrebbe? Grazie!

**Comment by Bazzu85** [comment]
> Dovrei aver risolto con l'ultimo commit, a breve dovrebbe uscire la nuova versione. Non appena è disponibile potresti verificare che funziona come dovrebbe? Grazie!

Risolto con la 1.5.4. Grazie mille
