### ISSUE TITLE
Problema con i titoli contenenti slash

### ISSUE THREAD

**Issue by RedSquirrel87** [CoffeeStraw/VVVVID-Downloader#7]
Ciao, volevo segnalare un problema su Unix con gli episodi che contengono slash (la barra obliqua "/") nel titolo. In caso ciò accada il programma lo considera come una sottocartella e di conseguenza la crea.
Ho verificato l'errore sull'episodio 36 di Death Note ( https://www.vvvvid.it/show/68/death-note ) intitolato "28/01", il programma andando a salvare il file come 28/01.mp4 ha creato in pratica la sottocartella chiamata "28" con al suo interno il file "01.mp4",
Penso si possa risolvere banalmente andando a sostituire o togliere eventuali slash nel titolo dell'episodio

**Comment by CoffeeStraw** [comment]
Ciao! Grazie della segnalazione, stupidamente pensavo che su Unix il problema non si presentasse (su Windows non dovrebbe accadere, avevo implementato [questa funzione](https://github.com/CoffeeStraw/VVVVID-Downloader/blob/master/text_utility.py#L9) proprio per evitarlo.

Appena ho tempo controllo i caratteri non validi su Unix e correggo, grazie della segnalazione!

**Comment by CoffeeStraw** [comment]
Pare che l'unico carattere non supportato sui sistemi UNIX [sia proprio lo '/'](https://stackoverflow.com/a/31976060) :)

Preparo un commit appena posso!

**Comment by RedSquirrel87** [comment]
Teoricamente oltre lo slash ci sono single e double dot (ossia "." e ".." che sono usati rispettivamente per indicare la cartella corrente o quella superiore), ma francamente dubito si incapperà mai in un episodio intitolato solo con uno o due punti xD

**Comment by CoffeeStraw** [comment]
Questo però solo se sono seguiti da / no?
Ad esepio, se il . ha del testo prima, serve come separatore per l'estensione.

**Comment by RedSquirrel87** [comment]
Si solo se sono unicamente presenti loro, in caso abbiano testo prima o dopo non danno problemi, e pensandoci solo ora visto che comunque il programma aggiunge l'estensione mp4 non capiterà comunque mai che siano presenti da soli, anche nel remotissimo caso l'episodio si intitolasse davvero così xD Quindi effettivamente non c'è da preoccuparsi su di loro. Unico appunto che mi viene in mente è che se il titolo del file comincia col punto viene visto come "file nascosto" su Unix (la convenzione del sistema operativo è appunto che i file il cui nome inizia col punto vengono flaggati come nascosti), quindi magari sarebbe utile anche un check sul fatto che il titolo inizi col punto e in quel caso per esempio anteporre un underscore "_" prima del punto per evitare che diventi file nascosto

**Comment by CoffeeStraw** [comment]
Non accadrà mai anche questo, ma è una buona osservazione!
Lo farò.
