### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by LukeSavefrogs** [CoffeeStraw/VVVVID-Downloader#8]
Ciao,
ho inserito il link di un anime nel file downloads_list.txt separandolo dagli esempi con una linea vuota.  
### Problema
Quando ho lanciato lo script con il comando `python main.py` ho ottenuto il seguente errore:

![image](https://user-images.githubusercontent.com/33452387/81502728-f68cb400-92df-11ea-83a7-dd923c366005.png)

### Analisi
Analizzando e risalendo nel codice ho trovato che il problema si trovava nel file `main.py` alla riga 167 dove, durante la **lettura del file**, venivano inviate alla funzione `dl_from_vvvvid` anche le **linee vuote** sotto forma di "/", facendo ritornare `None` (per assenza di match) alla regex contenuta nella funzione `parse_url` del file `vvvvid_scraper.py`. 
Questo causava l'errore `AttributeError` (vedi questo thread su [SO](https://stackoverflow.com/questions/7312020/why-wont-re-groups-give-me-anything-for-my-one-correctly-matched-group)) poichè non avendo match la funzione `.groups()` non aveva **capture groups** da ritornare.

### Soluzione
Per risolvere il problema basta aggiungere alla **riga 169** del file `main.py` un semplice controllo:
```python
if line.strip() == "":
    continue

```

Lo snippet della lettura del file diventerebbe quindi:
```python
	# Get anime list from local file, ignoring lines commented and empty lines
	with open("downloads_list.txt", 'r') as f:
		for line in f:
			if line.strip() == "":
				continue

			line = line.strip() + '/'
			if not line.startswith('#'):
				dl_from_vvvvid(line, requests_obj, ffmpeg_local)
```
Ho già testato il codice. Appena posso invierò una PR con la fix :)

**Comment by CoffeeStraw** [comment]
Ciao e... wow! È la PR più dettagliata che mi sia arriva finora, complimenti!
Ti ringrazio per la segnalazione, era un caso a cui non avevo pensato.
Si potrebbe unire questo nuovo controllo al sottostante (che verifica l'avere a che fare con una riga commentata o meno), in modo da avere meno dispersione ed evitare di chiamare il metodo `strip()` due volte.

**Comment by LukeSavefrogs** [comment]
Ottima idea... Ho committato un'altra versione sulla PR

**Comment by CoffeeStraw** [comment]
Effettuato il merge, chiudo!

**Comment by LukeSavefrogs** [comment]
Ho inviato la PR :)
Ho pensato che in futuro si potrebbe aggiungere un controllo per verificare che si tratti di un url valido. Ad esempio un utente potrebbe sbagliarsi e copiare **ttps://www.vvvvid.it/#!show/786/steinsgate-0** invece di **https://www.vvvvid.it/#!show/786/steinsgate-0** oppure **ww.vvvvid.it/#!show/786/steinsgate-0** invece di **www.vvvvid.it/#!show/786/steinsgate-0**. La differenza è sottile e, invece di trovarsi davanti ad un errore non parlante come

> Traceback (most recent call last):
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 176, in <module>
>     main()
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 171, in main
>     dl_from_vvvvid(line, requests_obj, ffmpeg_local)
>   File "d:/Programmi/VVVVID-Downloader-FORK/VVVVID-Downloader/main.py", line 30, in dl_from_vvvvid
>     show_id, url_name            = vvvvid_scraper.parse_url(url)
>   File "d:\Programmi\VVVVID-Downloader-FORK\VVVVID-Downloader\vvvvid_scraper.py", line 17, in parse_url
>     return re.search(pattern, url).groups()
> AttributeError: 'NoneType' object has no attribute 'groups'

gli si potrebbe presentare un messaggio del tipo: 

> URL non valido: ww.vvvvid.it/#!show/786/steinsgate-0


Questo anche perchè la tua regexp fa completo affidamento sul fatto che nell'url si trova "show", e in caso contrario restituisce il suddetto errore. Ciò significa che restituiscono errore anche URL come: 
- https://www.vvvvid.it/fandom/1/713/vvvvid-heroes/1216/541614/trailer
- https://www.vvvvid.it/fandom/5/242/horror-mania/231/541321/it-2-home-video
- https://www.vvvvid.it/channel/0/you/515708/video/l-attacco-dei-giganti-seconda-stagione-attacco-proiezione-sottomissione-e07

Quindi per il momento basterebbe aggiungere un controllo del tipo:
```python
if not re.match("(https?://)?www.vvvvid.it/show"):
    print("Errore - URL non valido: " + url)
```
Perlomeno in questo modo l'utente capisce che l'url non è supportato

![image](https://user-images.githubusercontent.com/33452387/81505619-e6310500-92f0-11ea-83f9-2c61872409c6.png)

**Comment by CoffeeStraw** [comment]
Ci stavo pensando proprio anche io, siamo sincronizzati ahahah!
Sì, ottima idea. Si potrebbe aprire una issue a parte in cui discutere di una regex sufficientemente robusta.

**Comment by LukeSavefrogs** [comment]
Ottimo ahahahah
Allora apro un issue separato :+1:
